"""Bright Data scraper for {{TARGET_URL}}.

Generated by the brightdata-scrape Kiro power. Customize selectors below.

Usage:
    from src.scrapers.{{TARGET_NAME}} import scrape_{{TARGET_NAME}}
    items = scrape_{{TARGET_NAME}}("https://example.com")
"""
from __future__ import annotations

import os
import time
from typing import Iterator, TypedDict

import requests
from bs4 import BeautifulSoup

API_KEY = os.environ["BRIGHTDATA_API_KEY"]
ZONE = os.environ.get("BRIGHTDATA_UNLOCKER_ZONE", "unblocker")
BASE_URL = "{{TARGET_URL}}"


class {{TARGET_NAME}}_Item(TypedDict, total=False):
    name: str
    url: str
    # TODO: add fields from {{FIELDS}}


def _fetch(url: str, retries: int = 3) -> str:
    """Fetch a page through Bright Data Web Unlocker with exponential backoff."""
    last_exc: Exception | None = None
    for attempt in range(retries):
        try:
            resp = requests.post(
                "https://api.brightdata.com/request",
                headers={"Authorization": f"Bearer {API_KEY}"},
                json={"zone": ZONE, "url": url, "format": "raw"},
                timeout=60,
            )
            resp.raise_for_status()
            return resp.text
        except requests.RequestException as exc:
            last_exc = exc
            time.sleep(2 ** attempt)
    raise RuntimeError(f"failed to fetch {url} after {retries} attempts") from last_exc


def _parse(html: str) -> list[{{TARGET_NAME}}_Item]:
    """Extract structured items from a page's HTML.

    Selectors come from Phase 2 reconnaissance. Adjust these to match the target site.
    """
    soup = BeautifulSoup(html, "html.parser")
    items: list[{{TARGET_NAME}}_Item] = []
    for card in soup.select(".item"):  # TODO: replace with {{SELECTORS}} root
        try:
            item: {{TARGET_NAME}}_Item = {
                "name": card.select_one(".name").get_text(strip=True),
                "url": card.select_one("a").get("href", ""),
                # TODO: extract remaining {{FIELDS}}
            }
            items.append(item)
        except (AttributeError, TypeError):
            continue
    return items


def _paginate(start_url: str, max_pages: int = 50) -> Iterator[str]:
    """Yield page URLs. Default: URL-based pagination (?page=N).

    Phase 2 chose pagination = {{PAGINATION}}. If different, replace the body.
    """
    for n in range(1, max_pages + 1):
        sep = "&" if "?" in start_url else "?"
        yield f"{start_url}{sep}page={n}"


def scrape_{{TARGET_NAME}}(start_url: str | None = None) -> list[{{TARGET_NAME}}_Item]:
    """Scrape {{TARGET_URL}} and return a list of items.

    Args:
        start_url: Override the default {{TARGET_URL}}.

    Returns:
        A list of typed item dicts.
    """
    url = start_url or BASE_URL
    all_items: list[{{TARGET_NAME}}_Item] = []
    for page_url in _paginate(url):
        html = _fetch(page_url)
        items = _parse(html)
        if not items:
            break
        all_items.extend(items)
    return all_items


if __name__ == "__main__":
    import json
    print(json.dumps(scrape_{{TARGET_NAME}}(), indent=2, ensure_ascii=False))
