"""Bright Data scraper for {{TARGET_URL}}.

Generated by the brightdata-scrape Kiro power. Customize selectors below.
This module uses html.parser from the Python standard library — no third-party
HTML parser required.

Usage:
    from src.scrapers.{{TARGET_NAME}} import scrape_{{TARGET_NAME}}
    items = scrape_{{TARGET_NAME}}("https://example.com")
"""
from __future__ import annotations

import os
import time
import urllib.request
import urllib.error
import json
from html.parser import HTMLParser
from typing import Iterator, TypedDict

API_KEY = os.environ["BRIGHTDATA_API_KEY"]
ZONE = os.environ.get("BRIGHTDATA_UNLOCKER_ZONE", "unblocker")
BASE_URL = "{{TARGET_URL}}"


class {{TARGET_NAME}}_Item(TypedDict, total=False):
    name: str
    url: str
    # TODO: add fields from {{FIELDS}}


class _ItemParser(HTMLParser):
    """Minimal HTMLParser subclass that collects items from the page.

    TODO: replace the class selector logic with real selectors from {{SELECTORS}}.
    Currently looks for <div class="item"> blocks and extracts name + href.
    """

    def __init__(self) -> None:
        super().__init__()
        self._items: list[{{TARGET_NAME}}_Item] = []
        self._in_item: bool = False
        self._in_name: bool = False
        self._current: {{TARGET_NAME}}_Item = {}

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr_dict = dict(attrs)
        classes = (attr_dict.get("class") or "").split()
        if tag == "div" and "item" in classes:  # TODO: replace with {{SELECTORS}} root
            self._in_item = True
            self._current = {}
        if self._in_item and tag == "a" and not self._current.get("url"):
            href = attr_dict.get("href")
            if href:
                self._current["url"] = href
        if self._in_item and tag in ("span", "h2", "h3") and "name" in classes:
            self._in_name = True

    def handle_endtag(self, tag: str) -> None:
        if tag in ("span", "h2", "h3"):
            self._in_name = False
        if tag == "div" and self._in_item:
            if self._current:
                self._items.append(self._current)
            self._in_item = False

    def handle_data(self, data: str) -> None:
        if self._in_name:
            existing = self._current.get("name", "")
            self._current["name"] = (existing + data).strip()

    def items(self) -> list[{{TARGET_NAME}}_Item]:
        return list(self._items)


def _fetch(url: str, retries: int = 3) -> str:
    """Fetch a page through Bright Data Web Unlocker with exponential backoff."""
    last_exc: Exception | None = None
    for attempt in range(retries):
        try:
            payload = json.dumps({"zone": ZONE, "url": url, "format": "raw"}).encode()
            req = urllib.request.Request(
                "https://api.brightdata.com/request",
                data=payload,
                headers={
                    "Authorization": f"Bearer {API_KEY}",
                    "Content-Type": "application/json",
                },
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=60) as resp:
                return resp.read().decode("utf-8", errors="replace")
        except (urllib.error.URLError, OSError) as exc:
            last_exc = exc
            time.sleep(2 ** attempt)
    raise RuntimeError(f"failed to fetch {url} after {retries} attempts") from last_exc


def _parse(html: str) -> list[{{TARGET_NAME}}_Item]:
    """Extract structured items from a page's HTML.

    Selectors come from Phase 2 reconnaissance. Adjust these to match the target site.
    """
    parser = _ItemParser()
    parser.feed(html)
    return parser.items()


def _paginate(start_url: str, max_pages: int = 50) -> Iterator[str]:
    """Yield page URLs. Default: URL-based pagination (?page=N).

    Phase 2 chose pagination = {{PAGINATION}}. If different, replace the body.
    """
    for n in range(1, max_pages + 1):
        sep = "&" if "?" in start_url else "?"
        yield f"{start_url}{sep}page={n}"


def scrape_{{TARGET_NAME}}(start_url: str | None = None) -> list[{{TARGET_NAME}}_Item]:
    """Scrape {{TARGET_URL}} and return a list of items.

    Args:
        start_url: Override the default {{TARGET_URL}}.

    Returns:
        A list of typed item dicts.
    """
    url = start_url or BASE_URL
    all_items: list[{{TARGET_NAME}}_Item] = []
    for page_url in _paginate(url):
        html = _fetch(page_url)
        items = _parse(html)
        if not items:
            break
        all_items.extend(items)
    return all_items


if __name__ == "__main__":
    print(json.dumps(scrape_{{TARGET_NAME}}(), indent=2, ensure_ascii=False))
