/**
 * Bright Data scraper for {{TARGET_URL}}.
 *
 * Generated by the brightdata-scrape Kiro power. Customize selectors below.
 *
 * Usage:
 *   import { scrape{{TARGET_NAME}} } from "@/scrapers/{{TARGET_NAME}}";
 *   const items = await scrape{{TARGET_NAME}}();
 */
import * as cheerio from "cheerio";

const API_KEY = process.env.BRIGHTDATA_API_KEY;
const ZONE = process.env.BRIGHTDATA_UNLOCKER_ZONE ?? "unblocker";
const BASE_URL = "{{TARGET_URL}}";

if (!API_KEY) {
  throw new Error("BRIGHTDATA_API_KEY is not set");
}

export interface {{TARGET_NAME}}_Item {
  name?: string;
  url?: string;
  // TODO: add fields from {{FIELDS}}
}

async function fetchPage(url: string, retries = 3): Promise<string> {
  for (let attempt = 0; attempt < retries; attempt++) {
    try {
      const resp = await fetch("https://api.brightdata.com/request", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ zone: ZONE, url, format: "raw" }),
      });
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
      return await resp.text();
    } catch (err) {
      if (attempt === retries - 1) throw err;
      await new Promise((r) => setTimeout(r, 2 ** attempt * 1000));
    }
  }
  throw new Error("unreachable");
}

function parseItems(html: string): {{TARGET_NAME}}_Item[] {
  const $ = cheerio.load(html);
  const items: {{TARGET_NAME}}_Item[] = [];
  $(".item").each((_i, el) => {
    // TODO: replace with {{SELECTORS}}
    const $el = $(el);
    items.push({
      name: $el.find(".name").text().trim(),
      url: $el.find("a").attr("href") ?? "",
      // TODO: extract remaining {{FIELDS}}
    });
  });
  return items;
}

function* paginate(startUrl: string, maxPages = 50): Generator<string> {
  for (let n = 1; n <= maxPages; n++) {
    const sep = startUrl.includes("?") ? "&" : "?";
    yield `${startUrl}${sep}page=${n}`;
  }
}

export async function scrape{{TARGET_NAME}}(
  startUrl: string = BASE_URL,
): Promise<{{TARGET_NAME}}_Item[]> {
  const all: {{TARGET_NAME}}_Item[] = [];
  for (const pageUrl of paginate(startUrl)) {
    const html = await fetchPage(pageUrl);
    const items = parseItems(html);
    if (items.length === 0) break;
    all.push(...items);
  }
  return all;
}
