/**
 * Bright Data scraper for {{TARGET_URL}}.
 *
 * Generated by the brightdata-scrape Kiro power. Customize selectors below.
 * This module uses the built-in fetch API and regex-based parsing — no
 * third-party HTML parser required.
 *
 * Usage:
 *   import { scrape{{TARGET_NAME}} } from "@/scrapers/{{TARGET_NAME}}";
 *   const items = await scrape{{TARGET_NAME}}();
 */

const API_KEY = process.env.BRIGHTDATA_API_KEY;
const ZONE = process.env.BRIGHTDATA_UNLOCKER_ZONE ?? "unblocker";
const BASE_URL = "{{TARGET_URL}}";

if (!API_KEY) {
  throw new Error("BRIGHTDATA_API_KEY is not set");
}

export interface {{TARGET_NAME}}_Item {
  name?: string;
  url?: string;
  // TODO: add fields from {{FIELDS}}
}

async function fetchPage(url: string, retries = 3): Promise<string> {
  for (let attempt = 0; attempt < retries; attempt++) {
    try {
      const resp = await fetch("https://api.brightdata.com/request", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ zone: ZONE, url, format: "raw" }),
      });
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
      return await resp.text();
    } catch (err) {
      if (attempt === retries - 1) throw err;
      await new Promise((r) => setTimeout(r, 2 ** attempt * 1000));
    }
  }
  throw new Error("unreachable");
}

function parseItems(html: string): {{TARGET_NAME}}_Item[] {
  const items: {{TARGET_NAME}}_Item[] = [];
  // TODO: replace with real selectors — adapt the regexes to match the target page structure.
  // Example: extract every <a> tag inside a container with class "item":
  //   const blockRe = /<div[^>]+class="item"[^>]*>([\s\S]*?)<\/div>/gi;
  //   const nameRe  = /<span[^>]+class="name"[^>]*>([^<]*)<\/span>/i;
  //   const hrefRe  = /<a[^>]+href="([^"]+)"/i;
  const blockRe = /<div[^>]+class="item"[^>]*>([\s\S]*?)<\/div>/gi;
  const nameRe = /<[^>]+class="name"[^>]*>([^<]*)</i;
  const hrefRe = /<a[^>]+href="([^"]+)"/i;

  let match: RegExpExecArray | null;
  while ((match = blockRe.exec(html)) !== null) {
    const block = match[1];
    const nameMatch = nameRe.exec(block);
    const hrefMatch = hrefRe.exec(block);
    items.push({
      name: nameMatch ? nameMatch[1].trim() : undefined,
      url: hrefMatch ? hrefMatch[1] : undefined,
      // TODO: extract remaining {{FIELDS}}
    });
  }
  return items;
}

function* paginate(startUrl: string, maxPages = 50): Generator<string> {
  for (let n = 1; n <= maxPages; n++) {
    const sep = startUrl.includes("?") ? "&" : "?";
    yield `${startUrl}${sep}page=${n}`;
  }
}

export async function scrape{{TARGET_NAME}}(
  startUrl: string = BASE_URL,
): Promise<{{TARGET_NAME}}_Item[]> {
  const all: {{TARGET_NAME}}_Item[] = [];
  for (const pageUrl of paginate(startUrl)) {
    const html = await fetchPage(pageUrl);
    const items = parseItems(html);
    if (items.length === 0) break;
    all.push(...items);
  }
  return all;
}
