"""Django function-based view — GET /api/scrape/

Generated by the brightdata-scrape Kiro power.
Calls into src/scrapers/{{TARGET_NAME}}.py

Wire it up in your urls.py:

    from django.urls import path
    from app.views.scrape import scrape

    urlpatterns = [
        path("api/scrape/", scrape, name="scrape"),
    ]
"""
from __future__ import annotations

import json

from django.http import HttpRequest, JsonResponse
from django.views.decorators.http import require_GET

from src.scrapers.{{TARGET_NAME}} import scrape_{{TARGET_NAME}}


@require_GET
def scrape(request: HttpRequest) -> JsonResponse:
    url: str | None = request.GET.get("url")
    try:
        items = scrape_{{TARGET_NAME}}(url) if url else scrape_{{TARGET_NAME}}()
    except Exception as exc:  # surface scraping failures as 500s
        return JsonResponse({"error": str(exc)}, status=500)
    return JsonResponse({"count": len(items), "items": items})
