/**
 * Express route — GET /scrape
 *
 * Generated by the brightdata-scrape Kiro power.
 * Calls into src/scrapers/{{TARGET_NAME}}.ts
 *
 * Wire it up in your app:
 *   import { scrapeRouter } from "./routes/scrape";
 *   app.use("/api", scrapeRouter);
 */
import { Router, Request, Response } from "express";
import { scrape{{TARGET_NAME}} } from "../scrapers/{{TARGET_NAME}}";

export const scrapeRouter = Router();

scrapeRouter.get("/scrape", async (req: Request, res: Response) => {
  const url =
    typeof req.query.url === "string" ? req.query.url : undefined;

  try {
    const items = await scrape{{TARGET_NAME}}(url);
    res.json({ count: items.length, items });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown error";
    res.status(500).json({ error: msg });
  }
});
