"""FastAPI route — GET /api/scrape

Generated by the brightdata-scrape Kiro power.
Calls into src/scrapers/{{TARGET_NAME}}.py

Wire it up by adding to your app:

    from app.api.scrape import router as scrape_router
    app.include_router(scrape_router, prefix="/api")
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException, Query

from src.scrapers.{{TARGET_NAME}} import scrape_{{TARGET_NAME}}

router = APIRouter()


@router.get("/scrape")
async def scrape(url: str | None = Query(default=None)) -> dict:
    try:
        items = scrape_{{TARGET_NAME}}(url) if url else scrape_{{TARGET_NAME}}()
    except Exception as exc:  # surface scraping failures as 500s
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    return {"count": len(items), "items": items}
