/**
 * Fastify plugin — GET /scrape
 *
 * Generated by the brightdata-scrape Kiro power.
 * Calls into src/scrapers/{{TARGET_NAME}}.ts
 *
 * Wire it up in your app:
 *   import Fastify from "fastify";
 *   import { scrapePlugin } from "./routes/scrape";
 *
 *   const app = Fastify();
 *   app.register(scrapePlugin, { prefix: "/api" });
 */
import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { scrape{{TARGET_NAME}} } from "../scrapers/{{TARGET_NAME}}";

export async function scrapePlugin(fastify: FastifyInstance): Promise<void> {
  fastify.get(
    "/scrape",
    async (
      request: FastifyRequest<{ Querystring: { url?: string } }>,
      reply: FastifyReply,
    ) => {
      const { url } = request.query;
      try {
        const items = await scrape{{TARGET_NAME}}(url);
        return { count: items.length, items };
      } catch (err) {
        const msg = err instanceof Error ? err.message : "unknown error";
        reply.status(500);
        return { error: msg };
      }
    },
  );
}
