"""Flask blueprint — GET /scrape

Generated by the brightdata-scrape Kiro power.
Calls into src/scrapers/{{TARGET_NAME}}.py

Wire it up by adding to your app factory:

    from app.api.scrape import bp as scrape_bp
    app.register_blueprint(scrape_bp, url_prefix="/api")
"""
from __future__ import annotations

from flask import Blueprint, jsonify, request

from src.scrapers.{{TARGET_NAME}} import scrape_{{TARGET_NAME}}

bp = Blueprint("scrape", __name__)


@bp.route("/scrape")
def scrape() -> tuple:
    url: str | None = request.args.get("url")
    try:
        items = scrape_{{TARGET_NAME}}(url) if url else scrape_{{TARGET_NAME}}()
    except Exception as exc:  # surface scraping failures as 500s
        return jsonify({"error": str(exc)}), 500
    return jsonify({"count": len(items), "items": items}), 200
