/**
 * Hono app — GET /scrape
 *
 * Generated by the brightdata-scrape Kiro power.
 * Calls into src/scrapers/{{TARGET_NAME}}.ts
 *
 * Wire it up in your main app:
 *   import { Hono } from "hono";
 *   import { scrapeApp } from "./routes/scrape";
 *
 *   const app = new Hono();
 *   app.route("/api", scrapeApp);
 */
import { Hono } from "hono";
import { scrape{{TARGET_NAME}} } from "../scrapers/{{TARGET_NAME}}";

export const scrapeApp = new Hono();

scrapeApp.get("/scrape", async (c) => {
  const url = c.req.query("url") ?? undefined;

  try {
    const items = await scrape{{TARGET_NAME}}(url);
    return c.json({ count: items.length, items });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown error";
    return c.json({ error: msg }, 500);
  }
});
