/**
 * Koa route — GET /scrape
 *
 * Generated by the brightdata-scrape Kiro power.
 * Calls into src/scrapers/{{TARGET_NAME}}.ts
 *
 * Dependencies: koa, @koa/router
 * Wire it up in your main app:
 *   import Koa from "koa";
 *   import { scrapeRouter } from "./routes/scrape";
 *
 *   const app = new Koa();
 *   app.use(scrapeRouter.routes()).use(scrapeRouter.allowedMethods());
 */
import Router from "@koa/router";
import type { Context } from "koa";
import { scrape{{TARGET_NAME}} } from "../scrapers/{{TARGET_NAME}}";

export const scrapeRouter = new Router({ prefix: "/api" });

scrapeRouter.get("/scrape", async (ctx: Context) => {
  const url =
    typeof ctx.query.url === "string" ? ctx.query.url : undefined;

  try {
    const items = await scrape{{TARGET_NAME}}(url);
    ctx.body = { count: items.length, items };
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown error";
    ctx.status = 500;
    ctx.body = { error: msg };
  }
});
