/**
 * Next.js App Router route — GET /api/scrape
 *
 * Generated by the brightdata-scrape Kiro power.
 * Calls into src/scrapers/{{TARGET_NAME}}.ts
 */
import { NextResponse } from "next/server";
import { scrape{{TARGET_NAME}} } from "@/scrapers/{{TARGET_NAME}}";

export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const url = searchParams.get("url") ?? undefined;

  try {
    const items = await scrape{{TARGET_NAME}}(url);
    return NextResponse.json({ count: items.length, items });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown error";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
