/**
 * Next.js Pages Router route — GET /api/scrape
 *
 * Generated by the brightdata-scrape Kiro power.
 * Calls into src/scrapers/{{TARGET_NAME}}.ts
 *
 * File location: pages/api/scrape.ts
 */
import type { NextApiRequest, NextApiResponse } from "next";
import { scrape{{TARGET_NAME}} } from "@/scrapers/{{TARGET_NAME}}";

type ResponseData =
  | { count: number; items: unknown[] }
  | { error: string };

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<ResponseData>,
) {
  if (req.method !== "GET") {
    res.setHeader("Allow", "GET");
    res.status(405).json({ error: "Method Not Allowed" });
    return;
  }

  const url =
    typeof req.query.url === "string" ? req.query.url : undefined;

  try {
    const items = await scrape{{TARGET_NAME}}(url);
    res.status(200).json({ count: items.length, items });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown error";
    res.status(500).json({ error: msg });
  }
}
