#!/usr/bin/env bash
# Bright Data Web Unlocker — generic fallback for languages without a first-class template.
#
# Generated by the brightdata-scrape Kiro power.
# Adapt this curl invocation into your language's HTTP client (Go's net/http,
# Ruby's Net::HTTP, Java's HttpClient, etc.). The contract is:
#
#   POST https://api.brightdata.com/request
#   Headers: Authorization: Bearer $BRIGHTDATA_API_KEY
#            Content-Type: application/json
#   Body:   {"zone": "<zone>", "url": "<target>", "format": "raw"}
#
#   Response: raw HTML body of the target page, or JSON if the target is a JSON endpoint.
#
# Translate the request, parse the HTML in your language's idiomatic parser
# (e.g., goquery for Go, Nokogiri for Ruby, jsoup for Java).

set -euo pipefail

: "${BRIGHTDATA_API_KEY:?BRIGHTDATA_API_KEY must be set}"
ZONE="${BRIGHTDATA_UNLOCKER_ZONE:-unblocker}"
TARGET_URL="{{TARGET_URL}}"

curl -s -X POST https://api.brightdata.com/request \
  -H "Authorization: Bearer ${BRIGHTDATA_API_KEY}" \
  -H "Content-Type: application/json" \
  -d "{\"zone\": \"${ZONE}\", \"url\": \"${TARGET_URL}\", \"format\": \"raw\"}"
