/**
 * Anthropic SDK tool definition for scraping {{TARGET_URL}}.
 *
 * Generated by the brightdata-scrape Kiro power.
 *
 * Usage:
 *   import Anthropic from "@anthropic-ai/sdk";
 *   import { scrapeTool, runScrapeTool } from "./tools/scrape";
 *
 *   const client = new Anthropic();
 *   const response = await client.messages.create({
 *     model: "claude-opus-4-7",
 *     max_tokens: 1024,
 *     tools: [scrapeTool],
 *     messages: [{ role: "user", content: "Scrape latest items from {{TARGET_URL}}" }],
 *   });
 *   // When the model returns a tool_use block:
 *   //   const result = await runScrapeTool(toolUse.input);
 */
import { scrape{{TARGET_NAME}} } from "../scrapers/{{TARGET_NAME}}";

export const scrapeTool = {
  name: "scrape_{{TARGET_NAME}}",
  description:
    "Scrape items from {{TARGET_URL}}. Use when the user asks for live data from this site. Returns a JSON list of items.",
  input_schema: {
    type: "object" as const,
    properties: {
      url: {
        type: "string",
        description:
          "Optional override URL. If omitted, scrapes the default starting URL ({{TARGET_URL}}).",
      },
    },
  },
};

export async function runScrapeTool(
  input: { url?: string },
): Promise<{ count: number; items: unknown[] }> {
  const items = await scrape{{TARGET_NAME}}(input.url);
  return { count: items.length, items };
}
