"""Anthropic SDK tool definition for scraping {{TARGET_URL}}.

Generated by the brightdata-scrape Kiro power.

Usage:
    import anthropic
    from src.tools.scrape import SCRAPE_TOOL, run_scrape_tool

    client = anthropic.Anthropic()
    response = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=1024,
        tools=[SCRAPE_TOOL],
        messages=[{"role": "user", "content": "Scrape latest items from {{TARGET_URL}}"}],
    )
    # When the model returns a tool_use block:
    #   result = run_scrape_tool(tool_use.input)
"""
from __future__ import annotations

from typing import Any

from src.scrapers.{{TARGET_NAME}} import scrape_{{TARGET_NAME}}

SCRAPE_TOOL: dict[str, Any] = {
    "name": "scrape_{{TARGET_NAME}}",
    "description": (
        "Scrape items from {{TARGET_URL}}. Use when the user asks for live data "
        "from this site. Returns a JSON list of items."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "url": {
                "type": "string",
                "description": (
                    "Optional override URL. If omitted, scrapes the default starting URL "
                    "({{TARGET_URL}})."
                ),
            },
        },
    },
}


def run_scrape_tool(tool_input: dict[str, Any]) -> dict[str, Any]:
    url = tool_input.get("url")
    items = scrape_{{TARGET_NAME}}(url) if url else scrape_{{TARGET_NAME}}()
    return {"count": len(items), "items": items}
