/**
 * LangChain tool definition for scraping {{TARGET_URL}}.
 *
 * Generated by the brightdata-scrape Kiro power.
 *
 * Usage:
 *   import { scrape{{TARGET_NAME}}Tool } from "./tools/scrape";
 *   const agent = await createReactAgent({ llm, tools: [scrape{{TARGET_NAME}}Tool] });
 */
import { tool } from "@langchain/core/tools";
import { z } from "zod";
import { scrape{{TARGET_NAME}} } from "../scrapers/{{TARGET_NAME}}";

export const scrape{{TARGET_NAME}}Tool = tool(
  async (input) => {
    const items = await scrape{{TARGET_NAME}}(input.url);
    return JSON.stringify({ count: items.length, items });
  },
  {
    name: "scrape_{{TARGET_NAME}}",
    description:
      "Scrape items from {{TARGET_URL}}. Use when the user asks for live data from this site. Returns a JSON list of items.",
    schema: z.object({
      url: z
        .string()
        .optional()
        .describe(
          "Optional override URL. If omitted, scrapes the default starting URL ({{TARGET_URL}}).",
        ),
    }),
  },
);
