"""LangChain tool definition for scraping {{TARGET_URL}}.

Generated by the brightdata-scrape Kiro power.

Usage:
    from src.tools.scrape import scrape_{{TARGET_NAME}}_tool

    from langchain.agents import AgentExecutor, create_react_agent
    agent = create_react_agent(llm, tools=[scrape_{{TARGET_NAME}}_tool])
"""
from __future__ import annotations

from typing import Optional, Type

from langchain_core.tools import BaseTool
from pydantic import BaseModel, Field

from src.scrapers.{{TARGET_NAME}} import scrape_{{TARGET_NAME}}


class _ScrapeInput(BaseModel):
    url: Optional[str] = Field(
        default=None,
        description=(
            "Optional override URL. If omitted, scrapes the default starting URL "
            "({{TARGET_URL}})."
        ),
    )


class _Scrape{{TARGET_NAME}}Tool(BaseTool):
    name: str = "scrape_{{TARGET_NAME}}"
    description: str = (
        "Scrape items from {{TARGET_URL}}. Use when the user asks for live data "
        "from this site. Returns a JSON list of items."
    )
    args_schema: Type[BaseModel] = _ScrapeInput

    def _run(self, url: Optional[str] = None) -> dict:
        items = scrape_{{TARGET_NAME}}(url) if url else scrape_{{TARGET_NAME}}()
        return {"count": len(items), "items": items}


scrape_{{TARGET_NAME}}_tool = _Scrape{{TARGET_NAME}}Tool()
