/**
 * Mastra tool definition for scraping {{TARGET_URL}}.
 *
 * Generated by the brightdata-scrape Kiro power.
 *
 * Usage:
 *   import { mastra } from "@/mastra";
 *   import { scrape{{TARGET_NAME}}Tool } from "./tools/scrape";
 *
 *   // Register in your Mastra instance:
 *   export const mastra = new Mastra({ tools: { scrape{{TARGET_NAME}}Tool } });
 *
 * Note: This template targets the Mastra v0.x / v1.x API.
 * If the Tool constructor signature has changed, refer to the official
 * Mastra docs at https://mastra.ai/docs and adjust accordingly.
 */
import { createTool } from "@mastra/core/tools";
import { z } from "zod";
import { scrape{{TARGET_NAME}} } from "../scrapers/{{TARGET_NAME}}";

export const scrape{{TARGET_NAME}}Tool = createTool({
  id: "scrape_{{TARGET_NAME}}",
  description:
    "Scrape items from {{TARGET_URL}}. Use when the user asks for live data from this site. Returns a JSON list of items.",
  inputSchema: z.object({
    url: z
      .string()
      .optional()
      .describe(
        "Optional override URL. If omitted, scrapes the default starting URL ({{TARGET_URL}}).",
      ),
  }),
  execute: async ({ context }) => {
    const items = await scrape{{TARGET_NAME}}(context.url);
    return { count: items.length, items };
  },
});
