"""OpenAI function-calling tool definition for scraping {{TARGET_URL}}.

Generated by the brightdata-scrape Kiro power.

Usage:
    from openai import OpenAI
    from src.tools.scrape import SCRAPE_TOOL, run_scrape_tool

    client = OpenAI()
    response = client.chat.completions.create(
        model="gpt-4o",
        tools=[SCRAPE_TOOL],
        messages=[{"role": "user", "content": "Scrape latest items from {{TARGET_URL}}"}],
    )
    # When the model calls the tool:
    #   import json
    #   args = json.loads(tool_call.function.arguments)
    #   result = run_scrape_tool(args)
"""
from __future__ import annotations

from typing import Any

from src.scrapers.{{TARGET_NAME}} import scrape_{{TARGET_NAME}}

SCRAPE_TOOL: dict[str, Any] = {
    "type": "function",
    "function": {
        "name": "scrape_{{TARGET_NAME}}",
        "description": (
            "Scrape items from {{TARGET_URL}}. Use when the user asks for live data "
            "from this site. Returns a JSON list of items."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "description": (
                        "Optional override URL. If omitted, scrapes the default starting URL "
                        "({{TARGET_URL}})."
                    ),
                },
            },
        },
    },
}


def run_scrape_tool(args: dict[str, Any]) -> dict[str, Any]:
    url = args.get("url")
    items = scrape_{{TARGET_NAME}}(url) if url else scrape_{{TARGET_NAME}}()
    return {"count": len(items), "items": items}
