/**
 * OpenAI function-calling tool definition for scraping {{TARGET_URL}}.
 *
 * Generated by the brightdata-scrape Kiro power.
 *
 * Usage:
 *   import OpenAI from "openai";
 *   import { scrapeTool, runScrapeTool } from "./tools/scrape";
 *
 *   const client = new OpenAI();
 *   const response = await client.chat.completions.create({
 *     model: "gpt-4o",
 *     tools: [scrapeTool],
 *     messages: [{ role: "user", content: "Scrape latest items from {{TARGET_URL}}" }],
 *   });
 *   // When the model calls the tool:
 *   //   const args = JSON.parse(toolCall.function.arguments);
 *   //   const result = await runScrapeTool(args);
 */
import { scrape{{TARGET_NAME}} } from "../scrapers/{{TARGET_NAME}}";

export const scrapeTool = {
  type: "function" as const,
  function: {
    name: "scrape_{{TARGET_NAME}}",
    description:
      "Scrape items from {{TARGET_URL}}. Use when the user asks for live data from this site. Returns a JSON list of items.",
    parameters: {
      type: "object",
      properties: {
        url: {
          type: "string",
          description:
            "Optional override URL. If omitted, scrapes the default starting URL ({{TARGET_URL}}).",
        },
      },
    },
  },
};

export async function runScrapeTool(
  args: { url?: string },
): Promise<{ count: number; items: unknown[] }> {
  const items = await scrape{{TARGET_NAME}}(args.url);
  return { count: items.length, items };
}
