/**
 * Vercel AI SDK tool definition for scraping {{TARGET_URL}}.
 *
 * Generated by the brightdata-scrape Kiro power.
 *
 * Usage:
 *   import { openai } from "@ai-sdk/openai";
 *   import { generateText } from "ai";
 *   import { scrape{{TARGET_NAME}}Tool } from "./tools/scrape";
 *
 *   const result = await generateText({
 *     model: openai("gpt-4o"),
 *     tools: { scrape{{TARGET_NAME}}: scrape{{TARGET_NAME}}Tool },
 *     prompt: "Scrape latest items from {{TARGET_URL}}",
 *   });
 */
import { tool } from "ai";
import { z } from "zod";
import { scrape{{TARGET_NAME}} } from "../scrapers/{{TARGET_NAME}}";

export const scrape{{TARGET_NAME}}Tool = tool({
  description:
    "Scrape items from {{TARGET_URL}}. Use when the user asks for live data from this site. Returns a JSON list of items.",
  parameters: z.object({
    url: z
      .string()
      .optional()
      .describe(
        "Optional override URL. If omitted, scrapes the default starting URL ({{TARGET_URL}}).",
      ),
  }),
  execute: async ({ url }) => {
    const items = await scrape{{TARGET_NAME}}(url);
    return { count: items.length, items };
  },
});
